version: 2

models:
  - name: fct_books_history
    columns:
      - name: book_sk
        tests:
          - not_null
          - unique
      - name: asin
        tests:
          - not_null
      - name: scraped_at
        tests:
          - not_null
      - name: title
        tests:
          - not_null

  - name: books_registry
    columns:
      - name: asin
        tests:
          - not_null
